### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jscamac** [jdyen/growmodr#3]
Hi Jian,
I thought I'd have a play around with this rather than build the models from scratch... but I'm having some issues in getting it to install.

The error:
`* installing *source* package ‘growmodr’ ...
** using staged installation
Error in .warning_nowrite(file.path(basename(pkgdir), ...)) : 
  (converted from warning) 'growmodr/R/stanmodels.R' already exists.  Not overwritten by rstantools.FALSE
Calls: <Anonymous> -> .add_stanfile -> .warning_nowrite
Execution halted
ERROR: configuration failed for package ‘growmodr’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/growmodr’
Error: Failed to install 'growmodr' from GitHub:
  (converted from warning) installation of package ‘/var/folders/3p/9_crb7sj0l3brz2rb_c34rv0fs59l1/T//Rtmp5cHzMB/file1630573b225d6/growmodr_0.1.0.tar.gz’ had non-zero exit status`

Note that I've got R 4.0.1 and rstan 2.21.2, rstan arm 2.21.2 and rstantools 2.1.1 and StanHeaders 2.21.0-6

**Comment by jdyen** [comment]
Hi Jimmy,

Try installing from here: https://github.com/jdyen/hier.growth. I set that up for Pete to deal with some changes in R 4.0.1 (name change is just because I don't like this name anymore -- will add a link from this repo when I get around to it).
